name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: "andronasef/annatools"
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 1
      - name: Get last commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_message=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
      - name: List files in the repository
        run: ls .
      - name: Create .env file
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env
          echo "BLOG_DATABASE_ID=${{ secrets.BLOG_DATABASE_ID }}" >> .env
          echo "TOOLS_CONTENT_DATABASE_ID=${{ secrets.TOOLS_CONTENT_DATABASE_ID }}" >> .env
          echo "PAGES_DATABASE_ID=${{ secrets.PAGES_DATABASE_ID }}" >> .env
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Build Project
        run: bun generate
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .output/public --project-name=annatools
          packageManager: bun
      - name: Job Summary
        run: |
          echo "## Build and Deploy" >> $GITHUB_STEP_SUMMARY
          echo "Commit Message: ${{ steps.get_commit_message.outputs.commit_message }}" >> $GITHUB_STEP_SUMMARY
