# https://github.com/actions/deploy-pages#usage
name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "andronasef/annatools"
          token: ${{ secrets.GH_PAT }}
      - name: List files in the repository
        run: |
            ls .
      - name: Create .env file      
        run:  |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env
          echo "BLOG_DATABASE_ID=${{ secrets.BLOG_DATABASE_ID }}" >> .env
          echo "TOOLS_CONTENT_DATABASE_ID=${{ secrets.TOOLS_CONTENT_DATABASE_ID }}" >> .env

      - name: install bun 
        uses: oven-sh/setup-bun@v1
        
      - name: Install Dependencies
        run:  bun install 
        
      - name: Build Project
        run: bunx nuxt generate
      
      # - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .output/public --project-name=annatools

  instant-index:
      needs: build
      runs-on: ubuntu-latest
      steps:
       - name: install bun 
         uses: oven-sh/setup-bun@v1

       - name: install indexer
         run: bun i -g google-indexing-script

       - name: run script
         run: GIS_CLIENT_EMAIL=${{ secrets.GIS_CLIENT_EMAIL }} GIS_PRIVATE_KEY=${{ secrets.GIS_PRIVATE_KEY }} gis annatools.me

 
          
