name: Google Instant Indexing
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Cloudflare Pages"]
    types:
      - completed

jobs:
  instant-index:
      runs-on: ubuntu-latest
      steps:
       - name: install node
         uses: actions/setup-node@v4
         
       - name: create service_account.json
         id: create-json
         uses: jsdaniell/create-json@v1.2.3
         with:
           name: "service_account.json"
           json: ${{ secrets.INDEXING_SECRET_FILE }}

       - name: install indexer
         run: npm i -g google-indexing-script

       - name: run script
         run: gis annatools.me --path ./service_account.json

 
