name: Google Instant Indexing
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Cloudflare Pages"]
    types:
      - completed

jobs:
  instant-index:
      runs-on: ubuntu-latest
      steps:
       - name: install node
         uses: actions/setup-node@v4

       - name: install indexer
         run: npm i -g google-indexing-script

       - name: run script
         run: GIS_CLIENT_EMAIL=${{ secrets.GIS_CLIENT_EMAIL }} GIS_PRIVATE_KEY=${{ secrets.GIS_PRIVATE_KEY }} gis annatools.me

 
