name: Instant Indexing X Index Now
on:
  workflow_dispatch:
  schedule:
    # Set the schedule time
    - cron: '0 2 * * *'


jobs:
  google-instant-index:
      runs-on: ubuntu-latest
      steps:
       - name: install node
         uses: actions/setup-node@v4
         
       - name: create service_account.json
         id: create-json
         uses: jsdaniell/create-json@v1.2.3
         with:
           name: "service_account.json"
           json: ${{ secrets.INDEXING_SECRET_FILE }}

       - name: install indexer
         run: npm i -g google-indexing-script

       - name: run script
         run: gis annatools.me --path ./service_account.json

  index-now:
    runs-on: ubuntu-latest
    steps:
    - uses: bojieyang/indexnow-action@v2
      with:
        sitemap-location: 'https://annatools.me/sitemap_index.xml' 
        key: ${{ secrets.INDEXNOW_KEY }} # The key you get from IndexNow.

