name: Google Instant Indexing
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Cloudflare Pages"]
    types:
      - completed

jobs:
  instant-index:
      runs-on: ubuntu-latest
      steps:
       - name: install node
         uses: actions/setup-node@v4
       - name: create secret file
         run: echo "${{secrets.INDEXING_SECRET_FILE}}" > ./service_account.json

       - name: install indexer
         run: npm i -g google-indexing-script

       - name: run script
         run: gis annatools.me --path ./service_account.json

 
